<?php
	$dia=date("d");
	$mes=date("m");
	$ano=date("Y");
	$Meses=array("Janeiro","Fevereiro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro");
	echo $dia." de ".$Meses[$mes-1]." de ".$ano;
?>
<!DOCTYPE html>
<html lang="pt-br">
<head>
	<title>Aula 16 Include</title>
	<meta charset="utf-8">
	<meta name="Author" content="Junior Cruz">
</head>
<body>

</body>
</html>